### ISSUE TITLE
Define Python version support matrix

### ISSUE THREAD

**Issue by ZhaoTzuHsien** [kalgory-com/kalgory-py#7]
Please define the Python versions that the kalgory-py library is compatible with.

**Comment by ChuWeiChang** [comment]
According to [Nuitka](https://github.com/Nuitka/Nuitka), python version must be >= 3.5. I will write it in readme.md later.
As for the packages, I will upload the requirement.txt once everything works out.

**Comment by ZhaoTzuHsien** [comment]
The support matrix is Python version >= 3.10
